e107inc/vstore

- js/vstore.js
- vstore.class.php
- vstore.php
> JS behaviors 

- js/vstore.js
> Issue #21 - Better way to init/re-init Zoom.

- e_sitelink.php
'cat' var is unknown var in e_url.php
> fix categories sitelink

- vstore.class.php
cat_sef needed for productList() function
> Missing cat_sef function

- admin_config.php
- e_sitelink.php
- templates/vstore_template.php
- vstore.class.php
**Moved into vstore_template**
- cart
- order_items
- nav bar cart
- categories
- shipping details
**Fixed issue with fix_sef()** again ...
Was pretty sure that i fixed this already a week or 2 before...
> Moved even more inline html code into the vstore_template file

- vstore.class.php
fix for wrong sum of item price & total amount
Complete payment now set order_status to pending
> fix for #36

- inc/admin_config_pref.php
Finished off adding support for GBP by adding GB Pounds as an option in Admin
> Add GBP in Admin drop down

- js/vstore.js
- shortcodes/batch/vstore_shortcodes.php
fixes the issue #92 concerning the missing currency symbol after variation change
> fixes #92: missing currency symbol after selecting variation

- inc/admin_config_cart.php
- inc/admin_config_cat.php
- inc/admin_config_coupons.php
- inc/admin_config_customer.php
- inc/admin_config_email_templates.php
- inc/admin_config_invoice.php
- inc/admin_config_items.php
- inc/admin_config_orders.php
- inc/admin_config_pref.php
- inc/admin_config_statistics.php
- inc/vstore_dashboard.class.php
Replaced all e107::getForm() with $this where applicable
> Fix frm to this

- inc/admin_config_cat.php
- inc/admin_config_item_vars.php
- inc/admin_config_items.php
- inc/admin_config_statistics.php
- js/vstore.js
- shortcodes/batch/vstore_shortcodes.php
- templates/vstore_template.php
- vstore.class.php
1. Implemented non-tracking item vars (Product options)
2. Fixed some typos, reordered some fields/tabs
3. Cleaned up some code
> Implemented non-tracking item vars (Product options)

- inc/admin_config_pref.php
- vstore.class.php
- vstore_menu.php
Implemented prefs for the vstore menu.
- product category to display the products from
- number of products to display in the menu
> Implemented prefs for the vstore menu.

- inc/admin_config_pref.php
- vstore_menu.php
Fixed some small issues in the vstore_menu.php and menu prefs
> Fix vstore menu

- shortcodes/batch/vstore_shortcodes.php
fixes #120: floatvals were not correctly parsed in case the main site language was not english
added $this->tp = e107::getParser() to __construct() to avoid repeatedly calls to that function (performance)
> fixes #120: floatvals were not correctly parsed in case

- shortcodes/batch/vstore_shortcodes.php
Implemented a solution to display the amounts according the locale number formats depending on the selected language
> Implemented a solution to display the amounts in locale format

- vstore.class.php
fixes #129: checking the extracted country code against the given country code
> fixes #129: checking the extracted country code

- inc/vstore_dashboard.class.php
fixes an issue with missing method errors, because the reference to e107::getForm() was missing.
Added $frm var to hold the e107::getForm() object.
> fixes an issue with missing method errors,

- vstore.class.php
> Reformat the vstore.class.php according PSR2 rules

- inc/admin_config_orders.php
- vstore.class.php
issue #116: Fixes refund issue in case automatic refunding is not supported by the payment method, e.g. bank transfer
> issue #116: Fixes refund issue in case automatic refunding is not supported

- inc/vstore_order.class.php
- vstore.class.php
* first implementation of the new vstore_order.class.php
* moved order related methods to the new class and updated vstore.class.php
> Implemented new vstore_order.class.php to process orders

- vstore.class.php
Implemented use of new e107::breadcrumb() method
> Magic breadcrumb

- e_sitelink.php
- shortcodes/batch/vstore_shortcodes.php
- templates/vstore_menu_template.php
- vstore_cat_menu.php
Added new categories menu
Uses e_sitelink to generate the data for the menu
Added new template vstore_menu_template.php
Added new shortcode to handle the categoriy data
> issue #142: Added new categories menu

- shortcodes/batch/vstore_shortcodes.php
- templates/vstore_dashboard_template.php
fixes #151 moved hardcoded dashboard nav to template
added nav-item and nav-link to template
> fixes #151 moved hardcoded dashboard nav to template

- e_sitelink.php
- shortcodes/batch/vstore_shortcodes.php
- templates/vstore_menu_template.php
added number of products to the sitelinks array (link_badge)
used link_badge in cat menu to display number of products in category
updated cat menu template
> issue #142 added number of products to the sitelinks array (link_badge)
